class skyui.defines.Form
{
    // Form Types
    public static var TYPE_NONE: Number = 0;

    public static var TYPE_EFFECTSETTING: Number = 18;

    public static var TYPE_ENCHANTMENT: Number = 21;
    public static var TYPE_SPELL: Number       = 22;
    public static var TYPE_SCROLLITEM: Number  = 23;

    public static var TYPE_ARMOR: Number = 26;
    public static var TYPE_BOOK: Number  = 27;

    public static var TYPE_INGREDIENT: Number = 30;
    public static var TYPE_LIGHT: Number      = 31;  //Torch
    public static var TYPE_MISC: Number       = 32;

    public static var TYPE_WEAPON: Number = 41;
    public static var TYPE_AMMO: Number   = 42;

    public static var TYPE_KEY: Number    = 45;
    public static var TYPE_POTION: Number = 46;

    public static var TYPE_SOULGEM: Number = 52;

    public static var TYPE_SHOUT: Number = 119;

    // Full formIds — used in switch(formId), compared against the raw 32-bit formId.
    // Skyrim.esm
    public static var FORMID_ITMPotionUse: Number                    = 0xB6435;
    public static var FORMID_AXE01: Number                           = 0x2F2F4;
    public static var FORMID_BOOKMAP1: Number                        = 0xDDEFB;
    public static var FORMID_BOOKMAP2: Number                        = 0xEF07A;
    public static var FORMID_BOOKMAP3: Number                        = 0xF33CD;
    public static var FORMID_BOOKMAP4: Number                        = 0xF33CE;
    public static var FORMID_BOOKMAP5: Number                        = 0xF33CF;
    public static var FORMID_BOOKMAP6: Number                        = 0xF33D0;
    public static var FORMID_BOOKMAP7: Number                        = 0xF33D1;
    public static var FORMID_BOOKMAP8: Number                        = 0xF33D2;
    public static var FORMID_BOOKMAP9: Number                        = 0xF33D3;
    public static var FORMID_BOOKMAP10: Number                       = 0xF33D4;
    public static var FORMID_BOOKMAP11: Number                       = 0xF33D5;
    public static var FORMID_BOOKMAP12: Number                       = 0xF33E0;
    public static var FORMID_BROKENWEAPON1: Number                   = 0xE72AA;
    public static var FORMID_BROKENWEAPON2: Number                   = 0xE72AC;
    public static var FORMID_BROKENWEAPON3: Number                   = 0xE72B0;
    public static var FORMID_BROKENWEAPON4: Number                   = 0xE72AE;
    public static var FORMID_BROKENWEAPON5: Number                   = 0xE72A6;
    public static var FORMID_BROKENWEAPON6: Number                   = 0xE72A8;
    public static var FORMID_BROKENWEAPON7: Number                   = 0xE72A0;
    public static var FORMID_BROKENWEAPON8: Number                   = 0xE729E;
    public static var FORMID_BROKENWEAPON9: Number                   = 0xE729A;
    public static var FORMID_BROKENWEAPON10: Number                  = 0xE729C;
    public static var FORMID_BROKENWEAPON11: Number                  = 0xE7296;
    public static var FORMID_BROKENWEAPON12: Number                  = 0xE7298;
    public static var FORMID_BROKENWEAPON13: Number                  = 0xE72A4;
    public static var FORMID_BROKENWEAPON14: Number                  = 0xE72A2;
    public static var FORMID_BROKENWEAPON15: Number                  = 0x64283;
    public static var FORMID_BROKENWEAPON16: Number                  = 0x64285;
    public static var FORMID_BROKENWEAPON17: Number                  = 0x64287;
    public static var FORMID_BROKENWEAPON18: Number                  = 0x64289;
    public static var FORMID_BROKENWEAPON19: Number                  = 0x6428B;
    public static var FORMID_BROKENWEAPON20: Number                  = 0x6428E;
    public static var FORMID_BROKENWEAPON21: Number                  = 0x64290;
    public static var FORMID_BROKENWEAPON22: Number                  = 0x64292;
    public static var FORMID_BROKENWEAPON23: Number                  = 0x64294;
    public static var FORMID_BROKENWEAPON24: Number                  = 0x64296;
    public static var FORMID_BROKENWEAPON25: Number                  = 0x64298;
    public static var FORMID_BROKENWEAPON26: Number                  = 0x6E806;
    public static var FORMID_BROKENWEAPON27: Number                  = 0xDB351;
    public static var FORMID_BROKENWEAPON28: Number                  = 0x240D3;
    public static var FORMID_BROKENWEAPON29: Number                  = 0x240D4;
    public static var FORMID_BROKENWEAPON30: Number                  = 0x240D5;
    public static var FORMID_BROKENWEAPON31: Number                  = 0x240D6;
    public static var FORMID_BUGJAR1: Number                         = 0xB08C7;
    public static var FORMID_BUGJAR2: Number                         = 0xFBC3A;
    public static var FORMID_BUGJAR3: Number                         = 0xFBC3B;
    public static var FORMID_BUGJAR4: Number                         = 0xFBC3C;
    public static var FORMID_BUGJAR5: Number                         = 0xFBC3D;
    public static var FORMID_CHITIN1: Number                         = 0x3AD57;
    public static var FORMID_CLOTHESWEDDINGWREATH: Number            = 0x8895A;
    public static var FORMID_CORALDRAGONCLAW: Number                 = 0xB634C;
    public static var FORMID_CWARROW: Number                         = 0x20DDF;
    public static var FORMID_CWARROWSHORT: Number                    = 0x20F02;
    public static var FORMID_DA01SOULGEMAZURASSTAR: Number           = 0x63B27;
    public static var FORMID_DA01SOULGEMBLACKSTAR: Number            = 0x63B29;
    public static var FORMID_DAEDRICARROW: Number                    = 0x139C0;
    public static var FORMID_DIAMONDCLAW: Number                     = 0xAB375;
    public static var FORMID_DRAUGRARROW: Number                     = 0x34182;
    public static var FORMID_DUNARCHERPRATICEARROW: Number           = 0xCAB52;
    public static var FORMID_DUNGEIRMUNDSIGDISARROWSILLUSION: Number = 0xE738A;
    public static var FORMID_DUNHALTEDSTREAMPOACHERSAXE: Number      = 0xAE086;
    public static var FORMID_DUNVOLUNRUUDPICKAXE: Number             = 0x1019D4;
    public static var FORMID_DWARVENARROW: Number                    = 0x139BC;
    public static var FORMID_DWARVENSCRAP1: Number                   = 0xC886C;
    public static var FORMID_DWARVENSCRAP2: Number                   = 0xC8878;
    public static var FORMID_DWARVENSCRAP3: Number                   = 0xC8864;
    public static var FORMID_DWARVENSCRAP4: Number                   = 0xC8872;
    public static var FORMID_DWARVENSCRAP5: Number                   = 0xC8866;
    public static var FORMID_DWARVENSCRAP6: Number                   = 0xC8874;
    public static var FORMID_DWARVENSCRAP7: Number                   = 0xC886A;
    public static var FORMID_DWARVENSCRAP8: Number                   = 0xAEBF1;
    public static var FORMID_DWARVENSCRAP9: Number                   = 0xC8861;
    public static var FORMID_DWARVENSCRAP10: Number                  = 0xC8868;
    public static var FORMID_DWARVENSCRAP11: Number                  = 0xC886E;
    public static var FORMID_DWARVENSCRAP12: Number                  = 0xC8870;
    public static var FORMID_DWARVENSPHEREARROW: Number              = 0x7B932;
    public static var FORMID_DWARVENSPHEREBOLT01: Number             = 0x7B935;
    public static var FORMID_DWARVENSPHEREBOLT02: Number             = 0x10EC8C;
    public static var FORMID_E3GOLDENCLAW: Number                    = 0x999E7;
    public static var FORMID_EBONYARROW: Number                      = 0x139BF;
    public static var FORMID_EBONYCLAW: Number                       = 0x5AF48;
    public static var FORMID_ELDERSCROLL1: Number                    = 0x2D513;
    public static var FORMID_ELDERSCROLL2: Number                    = 0x48782;
    public static var FORMID_ELVENARROW: Number                      = 0x139BD;
    public static var FORMID_EMERALDDRAGONCLAW: Number               = 0xED417;
    public static var FORMID_FALMERARROW: Number                     = 0x38341;
    public static var FORMID_FOLLOWERIRONARROW: Number               = 0x10E2DE;
    public static var FORMID_FORSWORNARROW: Number                   = 0xCEE9E;
    public static var FORMID_FORSWORNAXE: Number                     = 0xCC829;
    public static var FORMID_FORSWORNBOW: Number                     = 0xCEE9B;
    public static var FORMID_FORSWORNSTAFF: Number                   = 0xFA2C1;
    public static var FORMID_FORSWORNSWORD: Number                   = 0xCADE9;
    public static var FORMID_GEM1: Number                            = 0x1994F;
    public static var FORMID_GEM2: Number                            = 0x59654;
    public static var FORMID_GEM3: Number                            = 0x9DFBB;
    public static var FORMID_GEM4: Number                            = 0x9F7A6;
    public static var FORMID_GEMAMETHYSTFLAWLESS: Number             = 0x6851E;
    public static var FORMID_GLASSARROW: Number                      = 0x139BE;
    public static var FORMID_GLASSCLAW: Number                       = 0x7C260;
    public static var FORMID_GOLD001: Number                         = 0xF;
    public static var FORMID_INSTRUMENT1: Number                     = 0xDABA9;
    public static var FORMID_INSTRUMENT2: Number                     = 0xDABA7;
    public static var FORMID_INSTRUMENT3: Number                     = 0x105177;
    public static var FORMID_INSTRUMENT4: Number                     = 0x3292F;
    public static var FORMID_INSTRUMENT5: Number                     = 0x200BA;
    public static var FORMID_INSTRUMENT6: Number                     = 0xDABAB;
    public static var FORMID_INSTRUMENT7: Number                     = 0x200B6;
    public static var FORMID_INSTRUMENT8: Number                     = 0x105109;
    public static var FORMID_INSTRUMENT9: Number                     = 0xE77BB;
    public static var FORMID_DRAVINSBOW: Number                      = 0x6B9AD;
    public static var FORMID_HUNTINGBOW: Number                      = 0x13985;
    public static var FORMID_IRONARROW: Number                       = 0x1397D;
    public static var FORMID_IRONCLAW: Number                        = 0x8CDFA;
    public static var FORMID_IVORYDRAGONCLAW: Number                 = 0xAB7BB;
    public static var FORMID_LEATHER01: Number                       = 0xDB5D2;
    public static var FORMID_LEATHERSTRIPS: Number                   = 0x800E4;
    public static var FORMID_LOCKPICK: Number                        = 0xA;
    public static var FORMID_LONGBOW: Number                         = 0x3B562;
    public static var FORMID_MISCARTIFACT1: Number                   = 0x2C259;
    public static var FORMID_MISCARTIFACT2: Number                   = 0x2C25A;
    public static var FORMID_MISCAZURASSTAR: Number                  = 0x28AD7;
    public static var FORMID_MISCBOOK1: Number                       = 0xF1491;
    public static var FORMID_MISCBOOK2: Number                       = 0xCE70B;
    public static var FORMID_MISCBOOK3: Number                       = 0xE4897;
    public static var FORMID_MISCBOOK4: Number                       = 0xE3CB7;
    public static var FORMID_MISCMAP1: Number                        = 0x60CC2;
    public static var FORMID_MISCMAP2: Number                        = 0xBBCD5;
    public static var FORMID_MISCPOISON: Number                      = 0x2BAAB;
    public static var FORMID_MISCPOTION: Number                      = 0xC4F2E;
    public static var FORMID_MISCRING1: Number                       = 0x1CB34;
    public static var FORMID_MISCRING2: Number                       = 0xDA732;
    public static var FORMID_MISCRING3: Number                       = 0xDA733;
    public static var FORMID_MISCRING4: Number                       = 0xDA734;
    public static var FORMID_MISCRING5: Number                       = 0xDA735;
    public static var FORMID_MISCSCROLL1: Number                     = 0x457AB;
    public static var FORMID_MISCSCROLL2: Number                     = 0xDC530;
    public static var FORMID_MISCSCROLL3: Number                     = 0xDC52E;
    public static var FORMID_MQ101STEELARROW: Number                 = 0x105EE7;
    public static var FORMID_MS13GOLDENCLAW: Number                  = 0x39647;
    public static var FORMID_NORDHEROARROW: Number                   = 0xEAFDF;
    public static var FORMID_ORCISHARROW: Number                     = 0x139BB;
    public static var FORMID_ORE1: Number                            = 0x5ACDB;
    public static var FORMID_ORE2: Number                            = 0x5ACDC;
    public static var FORMID_ORE3: Number                            = 0x5ACDE;
    public static var FORMID_ORE4: Number                            = 0x71CF3;
    public static var FORMID_ORE5: Number                            = 0x5ACE1;
    public static var FORMID_ORE6: Number                            = 0x5ACE0;
    public static var FORMID_ORE7: Number                            = 0x5ACDD;
    public static var FORMID_ORE8: Number                            = 0x5ACE2;
    public static var FORMID_ORE9: Number                            = 0x5B2DF;
    public static var FORMID_ORE10: Number                           = 0x5ACDF;
    public static var FORMID_REMAINS1: Number                        = 0x75868;
    public static var FORMID_REMAINS2: Number                        = 0xF6767;
    public static var FORMID_REMAINS3: Number                        = 0xAADB6;
    public static var FORMID_REMAINS4: Number                        = 0xAADB7;
    public static var FORMID_REMAINS5: Number                        = 0x4286C;
    public static var FORMID_RUBYDRAGONCLAW: Number                  = 0x4B56C;
    public static var FORMID_SAPPHIREDRAGONCLAW: Number              = 0x663D7;
    public static var FORMID_SSDROCKSPLINTERPICKAXE: Number          = 0x6A707;
    public static var FORMID_STEELARROW: Number                      = 0x1397F;
    public static var FORMID_TRAPDART: Number                        = 0x236DD;
    public static var FORMID_WEAPPICKAXE: Number                     = 0xE3C16;
    // Update.esm (plugin 0x01)
    public static var FORMID_UPDATEHORSETACK1: Number = 0x010030C9;
    public static var FORMID_UPDATEHORSETACK2: Number = 0x010030CA;
    // Dawnguard.esm (plugin 0x02)
    public static var FORMID_DLC1CHITIN1: Number                 = 0x020195AA;
    public static var FORMID_DLC1CLOTHESVAMPIRELORDARMOR: Number = 0x02011A84;
    public static var FORMID_DLC1ELDERSCROLL1: Number            = 0x020126DC;
    public static var FORMID_DLC1ELDERSCROLL2: Number            = 0x02011A13;
    public static var FORMID_DLC1ELDERSCROLL3: Number            = 0x020118F9;
    public static var FORMID_DLC1ELVENARROWBLESSED: Number       = 0x020098A1;
    public static var FORMID_DLC1ELVENARROWBLOOD: Number         = 0x020098A0;
    public static var FORMID_DLC1GEM1: Number                    = 0x02012F97;
    public static var FORMID_DLC1GEM2: Number                    = 0x02012FC3;
    public static var FORMID_DLC1GEM3: Number                    = 0x02019ABB;
    public static var FORMID_DLC1GEM4: Number                    = 0x02019ABC;
    public static var FORMID_DLC1GEM5: Number                    = 0x02019ABD;
    public static var FORMID_DLC1REMAINS1: Number                = 0x02002993;
    public static var FORMID_DLC1REMAINS2: Number                = 0x02002994;
    public static var FORMID_DLC1REMAINS3: Number                = 0x02011CF7;
    public static var FORMID_DLC1REMAINS4: Number                = 0x02005704;
    public static var FORMID_DLC1REMAINS5: Number                = 0x02005705;
    public static var FORMID_DLC1REMAINS6: Number                = 0x02005706;
    public static var FORMID_DLC1REMAINS7: Number                = 0x02005707;
    public static var FORMID_TESTDLC1BOLT: Number                = 0x0200590C;
    // HearthFires.esm (plugin 0x03)
    public static var FORMID_HFHOUSEPART1: Number  = 0x03003043;
    public static var FORMID_HFHOUSEPART2: Number  = 0x03003035;
    public static var FORMID_HFHOUSEPART3: Number  = 0x03005A69;
    public static var FORMID_HFHOUSEPART4: Number  = 0x03003011;
    public static var FORMID_HFHOUSEPART5: Number  = 0x0300303F;
    public static var FORMID_HFHOUSEPART6: Number  = 0x03003012;
    public static var FORMID_HFHOUSEPART7: Number  = 0x0300300E;
    public static var FORMID_HFHOUSEPART8: Number  = 0x0300300F;
    public static var FORMID_HFHOUSEPART9: Number  = 0x0300306C;
    public static var FORMID_HFHOUSEPART10: Number = 0x03005A68;
    // Dragonborn.esm (plugin 0x04)
    public static var FORMID_DLC2BOOKMAP: Number             = 0x0401CAF2;
    public static var FORMID_DLC2CHITIN1: Number             = 0x0402B04E;
    public static var FORMID_DLC2DRAGONCLAW1: Number         = 0x0401CAC0;
    public static var FORMID_DLC2DRAGONCLAW2: Number         = 0x0401CAC1;
    public static var FORMID_DLC2DWARVENBALLISTABOLT: Number = 0x040339A1;
    public static var FORMID_DLC2GEM1: Number                = 0x0402145A;
    public static var FORMID_DLC2GEM2: Number                = 0x0403166F;
    public static var FORMID_DLC2GEM3: Number                = 0x04031670;
    public static var FORMID_DLC2GEM4: Number                = 0x04031671;
    public static var FORMID_DLC2GEM5: Number                = 0x04031672;
    public static var FORMID_DLC2INGREDIENT: Number          = 0x0401AAD6;
    public static var FORMID_DLC2MISCMAP: Number             = 0x0402BAAE;
    public static var FORMID_DLC2NETCHLEATHER: Number        = 0x0401CD7C;
    public static var FORMID_DLC2ORE1: Number                = 0x0402B06B;
    public static var FORMID_DLC2ORE2: Number                = 0x04017749;
    public static var FORMID_DLC2ORE3: Number                = 0x040195A9;
    public static var FORMID_DLC2PICKAXE1: Number            = 0x040179C9;
    public static var FORMID_DLC2PICKAXE2: Number            = 0x040206F2;
    public static var FORMID_DLC2PICKAXE3: Number            = 0x040398E6;
    public static var FORMID_DLC2RIEKLINGSPEARTHROWN: Number = 0x04017720;
    public static var FORMID_DLC2SCROLLSPIDER1: Number       = 0x0401445E;
    public static var FORMID_DLC2SCROLLSPIDER2: Number       = 0x04014480;
    public static var FORMID_DLC2SCROLLSPIDER3: Number       = 0x04016E1C;
    public static var FORMID_DLC2SCROLLSPIDER4: Number       = 0x0401707B;
    public static var FORMID_DLC2SCROLLSPIDER5: Number       = 0x0401952C;
    public static var FORMID_DLC2SCROLLSPIDER6: Number       = 0x04019534;
    public static var FORMID_DLC2SCROLLSPIDER7: Number       = 0x0401CAB0;
    public static var FORMID_DLC2SCROLLSPIDER8: Number       = 0x0401DA03;
    public static var FORMID_DLC2SCROLLSPIDER9: Number       = 0x040206D3;
    public static var FORMID_DLC2SCROLLSPIDER10: Number      = 0x040206D9;
    public static var FORMID_DLC2SCROLLSPIDER11: Number      = 0x040206DB;
    public static var FORMID_DLC2SCROLLSPIDER12: Number      = 0x0402095F;
    public static var FORMID_DLC2SCROLLSPIDER13: Number      = 0x04020960;
    public static var FORMID_DLC2SCROLLSPIDER14: Number      = 0x04020961;
    public static var FORMID_DLC2SCROLLSPIDER15: Number      = 0x04027490;
    public static var FORMID_DLC2SCROLLSPIDER16: Number      = 0x0402749D;
    public static var FORMID_DLC2SCROLLSPIDER17: Number      = 0x040274A5;
    public static var FORMID_DLC2SCROLLSPIDER18: Number      = 0x0403319E;
    public static var FORMID_DLC2SCROLLSPIDER19: Number      = 0x0403319F;
    public static var FORMID_DLC2SCROLLSPIDER20: Number      = 0x040331A0;
    public static var FORMID_DLC2SCROLLSPIDER21: Number      = 0x040331A1;
    public static var FORMID_DLC2SCROLLSPIDERMISC1: Number   = 0x04017719;
    public static var FORMID_DLC2SCROLLSPIDERMISC2: Number   = 0x0401771F;
    public static var FORMID_DLC2TROLLSKULL: Number          = 0x040247F9;

    // Base IDs — used in switch(baseId) where baseId = formId & 0xFFFFFF.
    // ccBGSSSE001-Fish.esm / ccTWBSSE001-PuzzleDungeon.esm
    public static var BASEID_CC001DWESCRAP: Number           = 0x804;
    public static var BASEID_CC001FISHBOOKMAP1: Number       = 0x70CCA;
    public static var BASEID_CC001FISHBOOKMAP2: Number       = 0x70CCB;
    public static var BASEID_CC001FISHBOOKMAP3: Number       = 0x70CCC;
    public static var BASEID_CC001FISHBOOKMAP4: Number       = 0x70CCD;
    public static var BASEID_CC001FISHBOOKMAP5: Number       = 0x70CCE;
    public static var BASEID_CC001FISHBOOKMAP6: Number       = 0x70CCF;
    public static var BASEID_CC001FISHBOOKMAP7: Number       = 0x70CD0;
    public static var BASEID_CC001FISHBOOKMAP8: Number       = 0x70CD1;
    public static var BASEID_CC001FISHBOOKMAP9: Number       = 0x70CD2;
    public static var BASEID_CC001FISHBOOKMAP10: Number      = 0x70CD3;
    public static var BASEID_CC001FISHBOOKMAP11: Number      = 0x70CD4;
    public static var BASEID_CC001FISHBOOKMAP12: Number      = 0x70CD5;
    public static var BASEID_CC001PUZZLEINGREDIENT1: Number  = 0x8B2;
    public static var BASEID_CC001PUZZLEINGREDIENT2: Number  = 0x8B8;
    public static var BASEID_CC001PUZZLEINGREDIENT3: Number  = 0x8B9;
    public static var BASEID_CC001PUZZLEINGREDIENT4: Number  = 0x8BA;
    public static var BASEID_CC001PUZZLEINGREDIENT5: Number  = 0x8BB;
    public static var BASEID_CC001PUZZLEINGREDIENT6: Number  = 0x8BC;
    public static var BASEID_CC001PUZZLEINGREDIENT7: Number  = 0x8BD;
    public static var BASEID_CC001PUZZLEINGREDIENT8: Number  = 0x8BE;
    public static var BASEID_CC001PUZZLEINGREDIENT9: Number  = 0x8BF;
    public static var BASEID_CC001PUZZLEINGREDIENT10: Number = 0x8C3;
    public static var BASEID_CC001PUZZLEINGREDIENT11: Number = 0x8C4;
    public static var BASEID_CC001PUZZLEINGREDIENT12: Number = 0x8C5;
    // ccBGSSSE025-AdvDSGS.esm
    public static var BASEID_CC025ADVDSGSRING: Number = 0x183E63;
    public static var BASEID_CC025BUGJAR1: Number     = 0x12DD3A;
    public static var BASEID_CC025BUGJAR2: Number     = 0x12DD3B;
    public static var BASEID_CC025BUGJAR3: Number     = 0x12DD3C;
    public static var BASEID_CC025ORE1: Number        = 0xBC6;
    public static var BASEID_CC025ORE2: Number        = 0xBC9;
    public static var BASEID_CC025SOULTOMATO1: Number = 0x804;
    public static var BASEID_CC025SOULTOMATO2: Number = 0x137F40;
    // ccBGSSSE031-AdvCyrus.esm
    public static var BASEID_CC031MISCMAP: Number = 0x80D;
    // ccBGSSSE067-DaedInv.esm
    public static var BASEID_CC067AYLEIDCRYSTAL1: Number      = 0x809;
    public static var BASEID_CC067AYLEIDCRYSTAL2: Number      = 0x762B7;
    public static var BASEID_CC067AYLEIDCRYSTAL3: Number      = 0x762B8;
    public static var BASEID_CC067AYLEIDCRYSTAL4: Number      = 0x762B9;
    public static var BASEID_CC067AYLEIDCRYSTAL5: Number      = 0x762BA;
    public static var BASEID_CC067AYLEIDCRYSTAL6: Number      = 0xBDB37;
    public static var BASEID_CC067AYLEIDCRYSTALPOTION: Number = 0x20E802;
    // ccASVSSE001-ALMSIVI.esm
    public static var BASEID_CCALMSIVIGEM1: Number   = 0x990ED;
    public static var BASEID_CCALMSIVIGEM2: Number   = 0x990F0;
    public static var BASEID_CCALMSIVIGEM3: Number   = 0x990F1;
    public static var BASEID_CCALMSIVIGEM4: Number   = 0x990F2;
    public static var BASEID_CCALMSIVIPOTION: Number = 0x82F;

    // ESL IDs — used in switch(eslId) where eslId = formId & 0xFFF, under case 0xFE.
    // ccBGSSSE019-StaffofSheogorath.esl
    public static var ESLID_CC019STAFFREMAINS: Number   = 0x80E;
    // ccBGSSSE036-PetBWolf.esl
    public static var ESLID_CC036PETWOLFREMAINS: Number = 0x80A;
    // ccKRTSSE001_Altar.esl
    public static var ESLID_CCKRTALTARGOLD: Number      = 0x81A;
    // ccVSVSSE002-Pets.esl
    public static var ESLID_CCVSV002PETAMULET: Number   = 0x871;
    public static var ESLID_CCVSV002PETGEAR: Number     = 0x851;

    // Equip Slots
    public static var EQUIP_RIGHT_HAND: Number  = 0x00013F42;
    public static var EQUIP_LEFT_HAND: Number   = 0x00013F43;
    public static var EQUIP_EITHER_HAND: Number = 0x00013F44;
    public static var EQUIP_BOTH_HANDS: Number  = 0x00013F45;
    public static var EQUIP_VOICE: Number       = 0x00025BEE;
}
