#[=======================================================================[.rst:
LinuxTools
----------

Linux-specific build support for SkyUI Community.

On Linux, the AS2/SWF pipeline runs natively via Java (FFDec).  The Papyrus
compiler (PapyrusCompiler.exe), PEX anonymizer (AFKPexAnon), and BSA packer
(bsarch) are Windows-only executables run through Proton's Wine implementation.

Variables consumed (all optional — auto-detected if absent):
  PROTON_WINE       Path to the Proton wine binary.
                    Default: searches system and Steam Proton install locations.
  STEAM_APP_ID      Steam App ID whose compatdata prefix is used as WINEPREFIX.
                    Default: 489830 (Skyrim Special Edition)

Variables produced:
  BSARCH_COMMAND          Proton wrapper script for bsarch.exe
  PEXANON_COMMAND         Proton wrapper script for AFKPexAnon.exe
  _PAPYRUS_GAME_DIR       Fake game dir containing "Papyrus Compiler/PapyrusCompiler.exe"
                          as a Proton wrapper; passed as GAME to Papyrus_Add on Linux.

#]=======================================================================]

if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    return()
endif()

message(STATUS "[Linux] Configuring Proton tool wrappers")

# ---------------------------------------------------------------------------
# Resolve Proton wine binary
# ---------------------------------------------------------------------------

if(NOT DEFINED PROTON_WINE OR PROTON_WINE STREQUAL "")
    # Search order: system Proton (e.g. CachyOS) → Steam-installed Proton builds
    find_program(PROTON_WINE wine
        PATHS
            "/usr/share/steam/compatibilitytools.d/proton-cachyos-slr/files/bin"
            "$ENV{HOME}/.local/share/Steam/steamapps/common/Proton - Experimental/files/bin"
            "$ENV{HOME}/.local/share/Steam/steamapps/common/Proton Hotfix/files/bin"
        NO_DEFAULT_PATH
    )
    if(NOT PROTON_WINE)
        file(GLOB _PROTON_DIRS
            "/usr/share/steam/compatibilitytools.d/*/files/bin"
            "$ENV{HOME}/.local/share/Steam/steamapps/common/Proton*/files/bin"
        )
        find_program(PROTON_WINE wine PATHS ${_PROTON_DIRS} NO_DEFAULT_PATH)
    endif()
endif()

if(NOT PROTON_WINE)
    message(FATAL_ERROR
        "[LinuxTools] Could not find a Proton wine binary.\n"
        "Set PROTON_WINE to the path of your Proton wine executable.\n"
        "Example: cmake --preset release -DPROTON_WINE=/path/to/proton/files/bin/wine")
endif()

message(STATUS "[Linux] Proton wine      : ${PROTON_WINE}")

# ---------------------------------------------------------------------------
# Resolve WINEPREFIX (Steam compatdata for the target App ID)
# ---------------------------------------------------------------------------

if(NOT DEFINED STEAM_APP_ID OR STEAM_APP_ID STREQUAL "")
    set(STEAM_APP_ID "489830")  # Skyrim Special Edition
endif()

set(_WINEPREFIX "$ENV{HOME}/.local/share/Steam/steamapps/compatdata/${STEAM_APP_ID}/pfx")
if(NOT EXISTS "${_WINEPREFIX}")
    message(FATAL_ERROR
        "[LinuxTools] WINEPREFIX '${_WINEPREFIX}' does not exist.\n"
        "Papyrus compilation and BSA packaging require a Proton prefix for App ID ${STEAM_APP_ID}.\n"
        "Launch Skyrim SE via Steam at least once to create it, then reconfigure.")
else()
    message(STATUS "[Linux] WINEPREFIX       : ${_WINEPREFIX}")
endif()

# ---------------------------------------------------------------------------
# Helper: generate a Proton wrapper script
#
# Usage:
#   _linux_make_proton_wrapper(
#       <output_script_path>
#       <exe_path_in_build_tree>
#   )
#
# The wrapper handles three cases that arise from BethesdaCMakeModules:
#
# 1. Plain Linux absolute paths (e.g. /home/user/build/foo.swf)
#    → Z:\home\user\build\foo.swf
#
# 2. key=value args whose value contains Linux paths, including
#    semicolon-separated path lists (e.g. --import=path1;path2;path3)
#    → Z:\ converted per-path component
#
# 3. Combined option blobs (BethesdaCMakeModules Caprica quirk):
#    PAPYRUS_COMPILER_ARGS is a CMake string. Unix Make/sh joins it into
#    one argument via backslash-space escaping. An arg like
#    "--game=skyrim --import=... --output=... --quiet" is re-split here
#    on " --" boundaries before forwarding to Proton.
# ---------------------------------------------------------------------------

function(_linux_make_proton_wrapper SCRIPT_PATH EXE_PATH)
    string(REPLACE "'" "'\\''" _SAFE_PROTON  "${PROTON_WINE}")
    string(REPLACE "'" "'\\''" _SAFE_PREFIX  "${_WINEPREFIX}")
    string(REPLACE "'" "'\\''" _SAFE_EXE     "${EXE_PATH}")

    set(_CONTENT "#!/usr/bin/env bash
# Auto-generated by cmake/LinuxTools.cmake — do not edit manually.
PROTON='${_SAFE_PROTON}'
WINEPREFIX='${_SAFE_PREFIX}'
EXE='${_SAFE_EXE}'

export WINEPREFIX

# Convert a single token: plain Linux path or key=value[;value...] paths.
_convert_token() {
    local arg=\"\$1\"
    if [[ \"\$arg\" == /* ]]; then
        # Unescape any CMake Makefile backslash-escaped spaces
        arg=\"\${arg//\\\\ / }\"
        printf '%s' \"Z:\$(printf '%s' \"\$arg\" | sed 's|/|\\\\\\\\|g')\"
    elif [[ \"\$arg\" == *=* ]]; then
        local key=\"\${arg%%=*}\"
        local val=\"\${arg#*=}\"
        local new_val=\"\"
        local sep=\"\"
        # Handle semicolon-separated path lists (e.g. --import=p1;p2;p3)
        IFS=';' read -ra PARTS <<< \"\$val\"
        for p in \"\${PARTS[@]}\"; do
            # Unescape any CMake Makefile backslash-escaped spaces (e.g. Skyrim\\ Special\\ Edition)
            p=\"\${p//\\\\ / }\"
            if [[ \"\$p\" == /* ]]; then
                p=\"Z:\$(printf '%s' \"\$p\" | sed 's|/|\\\\\\\\|g')\"
            fi
            new_val=\"\${new_val}\${sep}\${p}\"
            sep=';'
        done
        printf '%s' \"\${key}=\${new_val}\"
    else
        printf '%s' \"\$arg\"
    fi
}

PROTON_ARGS=()
for arg in \"\$@\"; do
    if [[ \"\$arg\" == -* ]] && [[ \"\$arg\" == *' -'* ]]; then
        # CMake Makefile generator joins flags as one backslash-space string; re-split on flag boundaries.
        # printf '%s\\n' prevents read from silently dropping the last token.
        while IFS= read -r part; do
            [[ -n \"\$part\" ]] && PROTON_ARGS+=(\"\$(_convert_token \"\$part\")\")
        done < <(printf '%s\\n' \"\$arg\" | sed -E 's/ (-{1,2}[[:alpha:]])/\\n\\1/g')
    else
        PROTON_ARGS+=(\"\$(_convert_token \"\$arg\")\")
    fi
done

exec \"\$PROTON\" \"\$EXE\" \"\${PROTON_ARGS[@]}\"
")
    # Avoid spurious downstream rebuilds — skip write if content is unchanged.
    if(EXISTS "${SCRIPT_PATH}")
        file(READ "${SCRIPT_PATH}" _EXISTING_CONTENT)
        if("${_EXISTING_CONTENT}" STREQUAL "${_CONTENT}")
            return()
        endif()
    endif()
    file(WRITE "${SCRIPT_PATH}" "${_CONTENT}")
    file(CHMOD "${SCRIPT_PATH}"
        PERMISSIONS
            OWNER_READ OWNER_WRITE OWNER_EXECUTE
            GROUP_READ GROUP_EXECUTE
            WORLD_READ WORLD_EXECUTE
    )
endfunction()

# ---------------------------------------------------------------------------
# Tool output directory in the build tree
# ---------------------------------------------------------------------------

set(_LINUX_TOOLS_DIR "${CMAKE_BINARY_DIR}/tools/linux")
file(MAKE_DIRECTORY "${_LINUX_TOOLS_DIR}")

# ---------------------------------------------------------------------------
# bsarch.exe — BSA packer
# ---------------------------------------------------------------------------

set(_BSARCH_EXE "${CMAKE_BINARY_DIR}/tools/bsarch.exe")

if(NOT EXISTS "${_BSARCH_EXE}")
    message(STATUS "[Linux] Downloading bsarch.exe ...")
    file(DOWNLOAD
        "https://github.com/TES5Edit/TES5Edit/raw/b3235062f275a7d4a94162af910923ba79f0e77a/Tools/BSArchive/bsarch.exe"
        "${_BSARCH_EXE}"
        EXPECTED_HASH SHA3_224=87e25b2c8b6c90c00d3a2141ec2130a97daa184aff5f2d3d6595c872
        STATUS _BSARCH_STATUS
    )
    list(GET _BSARCH_STATUS 0 _BSARCH_ERR)
    if(_BSARCH_ERR)
        list(GET _BSARCH_STATUS 1 _BSARCH_MSG)
        message(FATAL_ERROR "[LinuxTools] Failed to download bsarch.exe: ${_BSARCH_MSG}")
    endif()
endif()

set(_BSARCH_WRAPPER "${_LINUX_TOOLS_DIR}/bsarch")
_linux_make_proton_wrapper("${_BSARCH_WRAPPER}" "${_BSARCH_EXE}")

set(BSARCH_COMMAND "${_BSARCH_WRAPPER}" CACHE FILEPATH "bsarch Proton wrapper" FORCE)
message(STATUS "[Linux] bsarch wrapper   : ${_BSARCH_WRAPPER}")

# ---------------------------------------------------------------------------
# PapyrusCompiler.exe — Papyrus compiler (bundled with Skyrim SE)
#
# Papyrus.cmake resolves the compiler as <GAME>/Papyrus Compiler/PapyrusCompiler.exe,
# so this wrapper dir must mirror that layout with a Proton wrapper in place of the exe.
# ---------------------------------------------------------------------------

set(_PAPYRUS_COMPILER_EXE "${SkyrimSE_PATH}/Papyrus Compiler/PapyrusCompiler.exe")
if(NOT EXISTS "${_PAPYRUS_COMPILER_EXE}")
    message(FATAL_ERROR
        "[LinuxTools] PapyrusCompiler.exe not found at '${_PAPYRUS_COMPILER_EXE}'.\n"
        "Ensure Skyrim Special Edition is installed and SkyrimSE_PATH is set correctly.")
endif()

set(_PAPYRUS_WRAPPER_DIR "${CMAKE_BINARY_DIR}/tools/papyrus-wrapper/Papyrus Compiler")
file(MAKE_DIRECTORY "${_PAPYRUS_WRAPPER_DIR}")
set(_PAPYRUS_WRAPPER "${_PAPYRUS_WRAPPER_DIR}/PapyrusCompiler.exe")
_linux_make_proton_wrapper("${_PAPYRUS_WRAPPER}" "${_PAPYRUS_COMPILER_EXE}")

set(_PAPYRUS_GAME_DIR "${CMAKE_BINARY_DIR}/tools/papyrus-wrapper")
message(STATUS "[Linux] PapyrusCompiler  : ${_PAPYRUS_WRAPPER}")

# ---------------------------------------------------------------------------
# AFKPexAnon.exe — PEX anonymizer
# ---------------------------------------------------------------------------

set(_PEXANON_DIR "${CMAKE_BINARY_DIR}/tools/AFKPexAnon")
set(_PEXANON_EXE "${_PEXANON_DIR}/AFKPexAnon.exe")

if(NOT EXISTS "${_PEXANON_EXE}")
    message(STATUS "[Linux] Downloading AFKPexAnon ...")
    set(_PEXANON_ARCHIVE "${CMAKE_BINARY_DIR}/download/AFKPexAnon-1.1.0-x64.7z")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/download")
    file(DOWNLOAD
        "https://github.com/namralkeeg/AFKPexAnon/releases/download/v1.1.0/AFKPexAnon-1.1.0-x64.7z"
        "${_PEXANON_ARCHIVE}"
        EXPECTED_HASH SHA3_224=48721850d462232f2b0e3da91055fbb014b88590a50dac36965c1143
        STATUS _PEXANON_STATUS
    )
    list(GET _PEXANON_STATUS 0 _PEXANON_ERR)
    if(_PEXANON_ERR)
        list(GET _PEXANON_STATUS 1 _PEXANON_MSG)
        message(FATAL_ERROR "[LinuxTools] Failed to download AFKPexAnon: ${_PEXANON_MSG}")
    endif()
    file(ARCHIVE_EXTRACT INPUT "${_PEXANON_ARCHIVE}" DESTINATION "${_PEXANON_DIR}")
endif()

set(_PEXANON_WRAPPER "${_LINUX_TOOLS_DIR}/AFKPexAnon")
_linux_make_proton_wrapper("${_PEXANON_WRAPPER}" "${_PEXANON_EXE}")

set(PEXANON_COMMAND "${_PEXANON_WRAPPER}" CACHE FILEPATH "AFKPexAnon Proton wrapper" FORCE)
message(STATUS "[Linux] AFKPexAnon wrap  : ${_PEXANON_WRAPPER}")
